### ISSUE TITLE
Tool not working with my server

### ISSUE THREAD

**Issue by Zimtex** [Mista-Tea/improved-stacker#3] opened 2015-05-21 22:31 UTC
When I install the stacker tool on my server, it removes all the default tools. Any help?

**Comment by Mista-Tea** [comment] 2015-05-24 20:53
You're absolutely sure that Stacker Improved is the cause and no other addons?

If yes, can you provide some screenshots showing your tool menu and whatever else is being affected? I'm afraid I've never heard of this happening before, much less due to my tool, so I need a little more information.

Thanks

**Comment by Mista-Tea** [comment] 2015-07-01 02:16
I haven't received any further word from you concerning this issue, nor have I heard of anyone else encountering it. I am closing this for now.

**Closed by Mista-Tea** 2015-07-01 02:16 UTC
